# Uncomment the next line to define a global platform for your project
# platform :ios

target 'myVK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myVK
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'PromiseKit'
end
